# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: pipelines/build.yml
  - template: pipelines/e2e.yml

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: pipelines/build.yml
  - template: pipelines/e2e.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: pipelines/build.yml
  - template: pipelines/e2e.yml
