steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install (root)'

- script: npm install
  workingDirectory: $(Build.SourcesDirectory)/packages/build-electron
  displayName: 'npm install (build-electron package)'

- script: npm install
  workingDirectory: $(Build.SourcesDirectory)/packages/schematics
  displayName: 'npm install (schematics package)'

- script: npm run build
  displayName: 'npm build'
  continueOnError: true

- script: npm run lint
  displayName: 'npm lint'

- script: npm run test
  displayName: 'npm test'
